// <auto-generated />
namespace CobanaEnergy.Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addingcontractid86c5md48r : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingcontractid86c5md48r));
        
        string IMigrationMetadata.Id
        {
            get { return "202510271412016_adding-contractid-86c5md48r"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
